manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: joaopedropio
      url-base: https://github.com/joaopedropio
    - name: gpeye                         #new entry
      url-base: https://github.com/praconly #new entry
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: snake-module
      remote: joaopedropio
      revision: zephyr-4.1
    - name: urchin-peripheral-animation
      remote: praconly
      revision: main
  self:
    path: config
